name: Staging deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd public_html
            source ~/.bashrc
            git checkout main
            git pull origin main
            composer install
            npm install
            npx yarn build
            php bin/console doctrine:migrations:migrate --no-interaction
